targetScope = 'resourceGroup'

@description('Location for all resources')
param location string = resourceGroup().location

@description('Log Analytics workspace name — auto-generated by the imperative env creation; parameterized so a clean rebuild can pass a nicer name')
param logAnalyticsName string = 'workspace-rgrecipeplanner6NWg'

@description('Container image with tag')
param containerImage string = 'ghcr.io/carlovinci17/recipe-planner:latest'

@description('GitHub Container Registry username')
param ghcrUsername string = 'carlovinci17'

@secure()
@description('GitHub PAT (read:packages) to pull the private image')
param ghcrPullToken string

@description('Public Supabase URL (NEXT_PUBLIC — safe, ships to browser)')
param supabaseUrl string = 'https://ykfcbebqwwhziqgfkrlz.supabase.co'

@description('Key Vault name — globally unique, so override it for a fresh deploy')
param keyVaultName string = 'kv-recipe-iac'

@secure()
@description('Public Supabase anon key')
param supabaseAnonKey string

@secure()
param supabaseServiceRoleKey string

@secure()
param anthropicApiKey string

@secure()
param googleClientId string

@secure()
param googleClientSecret string

@secure()
param inngestEventKey string


// ── Log Analytics workspace — backing store for logs & metrics ──
resource logWorkspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
  }
}

// ── Application Insights (2.6) — workspace-based APM ──
resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: 'appi-recipe-planner'
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logWorkspace.id
  }
}

// ── Container Apps environment — ships container logs to Log Analytics ──
resource containerEnv 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: 'cae-recipe-planner'
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logWorkspace.properties.customerId
        sharedKey: logWorkspace.listKeys().primarySharedKey
      }
    }
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
      }
    ]
  }
}

var kvUri = keyVault.properties.vaultUri   // https://kv-recipe-planner.vault.azure.net/

resource containerApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: 'recipe-planner'
  location: location
  identity: {                                   // ← attach the app's managed identity
    type: 'UserAssigned'
    userAssignedIdentities: { '${appIdentity.id}': {} }
  }
  properties: {
    managedEnvironmentId: containerEnv.id       // ← reference → deploys after the env
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 3000
        traffic: [ { latestRevision: true, weight: 100 } ]
      }
      registries: [ {
        server: 'ghcr.io'
        username: ghcrUsername
        passwordSecretRef: 'ghcr-pull-token'
      } ]
      secrets: [
        { name: 'ghcr-pull-token', value: ghcrPullToken }              // registry PAT (secure param)
        // Key Vault references — resolved by the app identity (no values here):
        { name: 'supabase-service-role-key', keyVaultUrl: '${kvUri}secrets/supabase-service-role-key', identity: appIdentity.id }
        { name: 'anthropic-api-key',         keyVaultUrl: '${kvUri}secrets/anthropic-api-key',         identity: appIdentity.id }
        { name: 'google-client-id',          keyVaultUrl: '${kvUri}secrets/google-client-id',          identity: appIdentity.id }
        { name: 'google-client-secret',      keyVaultUrl: '${kvUri}secrets/google-client-secret',      identity: appIdentity.id }
        { name: 'inngest-event-key',         keyVaultUrl: '${kvUri}secrets/inngest-event-key',         identity: appIdentity.id }
        { name: 'appinsights-connection-string', keyVaultUrl: '${kvUri}secrets/appinsights-connection-string', identity: appIdentity.id }
      ]
    }
    template: {
      containers: [ {
        name: 'recipe-planner'
        image: containerImage
        resources: { cpu: json('0.5'), memory: '1Gi' }
        env: [
          { name: 'NEXT_PUBLIC_SUPABASE_URL', value: supabaseUrl }
          { name: 'NEXT_PUBLIC_SUPABASE_ANON_KEY', value: supabaseAnonKey }
          { name: 'NODE_ENV', value: 'production' }
          { name: 'SUPABASE_SERVICE_ROLE_KEY', secretRef: 'supabase-service-role-key' }
          { name: 'ANTHROPIC_API_KEY', secretRef: 'anthropic-api-key' }
          { name: 'GOOGLE_CLIENT_ID', secretRef: 'google-client-id' }
          { name: 'GOOGLE_CLIENT_SECRET', secretRef: 'google-client-secret' }
          { name: 'INNGEST_EVENT_KEY', secretRef: 'inngest-event-key' }
          { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', secretRef: 'appinsights-connection-string' }
        ]
      } ]
      scale: { minReplicas: 1, maxReplicas: 3 }
    }
  }
}


// ── Managed identities ─────────────────────────────────────────────
// The app's identity — reads secrets from Key Vault (Lesson 2.3)
resource appIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: 'id-recipe-planner'
  location: location
}

// The CI deploy identity — GitHub OIDC → Container Apps (Lesson 2.5)
resource deployIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: 'id-github-deploy'
  location: location
}

// ── Key Vault (RBAC authorization) — holds the app's secrets (2.3) ──
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    tenantId: subscription().tenantId
    sku: {
      family: 'A'
      name: 'standard'
    }
    enableRbacAuthorization: true
  }
}

resource sSvcRole  'Microsoft.KeyVault/vaults/secrets@2023-07-01' = { parent: keyVault, name: 'supabase-service-role-key', properties: { value: supabaseServiceRoleKey } }
resource sAnthropic 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = { parent: keyVault, name: 'anthropic-api-key',         properties: { value: anthropicApiKey } }
resource sGId      'Microsoft.KeyVault/vaults/secrets@2023-07-01' = { parent: keyVault, name: 'google-client-id',          properties: { value: googleClientId } }
resource sGSecret  'Microsoft.KeyVault/vaults/secrets@2023-07-01' = { parent: keyVault, name: 'google-client-secret',      properties: { value: googleClientSecret } }
resource sInngest  'Microsoft.KeyVault/vaults/secrets@2023-07-01' = { parent: keyVault, name: 'inngest-event-key',         properties: { value: inngestEventKey } }
// App Insights connection string — pulled from the freshly-created resource (no param!)
resource sAppI     'Microsoft.KeyVault/vaults/secrets@2023-07-01' = { parent: keyVault, name: 'appinsights-connection-string', properties: { value: appInsights.properties.ConnectionString } }


// Built-in role IDs
var kvSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'
var contributorRoleId   = 'b24988ac-6180-42a0-ab88-20f7382dd24c'

// app identity → Key Vault Secrets User (read secrets)
resource appKvRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, appIdentity.id, kvSecretsUserRoleId)
  scope: keyVault
  properties: {
    principalId: appIdentity.properties.principalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', kvSecretsUserRoleId)
    principalType: 'ServicePrincipal'
  }
}

// deploy identity → Contributor on the resource group
resource deployRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(resourceGroup().id, deployIdentity.id, contributorRoleId)
  scope: resourceGroup()
  properties: {
    principalId: deployIdentity.properties.principalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', contributorRoleId)
    principalType: 'ServicePrincipal'
  }
}

// GitHub OIDC federated credential on the deploy identity (2.5)
resource deployFic 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2023-01-31' = {
  parent: deployIdentity
  name: 'gh-version2-plan'
  properties: {
    issuer: 'https://token.actions.githubusercontent.com'
    subject: 'repo:carlovinci17/recipe-planner-app:ref:refs/heads/version2/plan'
    audiences: [ 'api://AzureADTokenExchange' ]
  }
}
