targetScope = 'resourceGroup'

@description('Location for all resources')
param location string = resourceGroup().location

@description('Log Analytics workspace name — auto-generated by the imperative env creation; parameterized so a clean rebuild can pass a nicer name')
param logAnalyticsName string = 'workspace-rgrecipeplanner6NWg'

@description('Container image with tag. NO DEFAULT on purpose: CI owns this value and pins it to a commit SHA on every deploy, so a `:latest` default here would silently roll production to a different build. Pass the current tag, which `az containerapp show -n recipe-planner -g rg-recipe-planner --query properties.template.containers[0].image -o tsv` prints.')
param containerImage string

@description('GitHub Container Registry username')
param ghcrUsername string = 'carlovinci17'

@secure()
@description('GitHub PAT (read:packages) to pull the private image')
param ghcrPullToken string

@description('Key Vault name — globally unique, so override it for a fresh deploy. Defaults to the LIVE vault: the previous default (kv-recipe-iac) named a vault that does not exist, so every `keyVaultUrl` secret reference below resolved to the wrong host and the container app could not have read a single secret.')
param keyVaultName string = 'kv-recipe-planner'

@description('The app\'s own public URL. Feeds both NEXT_PUBLIC_APP_URL and AUTH_URL (Auth.js builds its sign-in redirect from the latter, so it must match a redirect URI registered on the Entra app). Cannot be derived from the container app\'s ingress FQDN here — that would be a resource referencing itself — so it is a parameter whose default is the live value.')
param appPublicUrl string = 'https://recipe-planner.delightfulrock-67fe0b09.australiaeast.azurecontainerapps.io'


// ── Log Analytics workspace — backing store for logs & metrics ──
resource logWorkspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
  }
}

// ── Application Insights (2.6) — workspace-based APM ──
resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: 'appi-recipe-planner'
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logWorkspace.id
  }
}

// ── Container Apps environment — ships container logs to Log Analytics ──
resource containerEnv 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: 'cae-recipe-planner'
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logWorkspace.properties.customerId
        sharedKey: logWorkspace.listKeys().primarySharedKey
      }
    }
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
      }
    ]
  }
}

var kvUri = keyVault.properties.vaultUri   // https://kv-recipe-planner.vault.azure.net/

resource containerApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: 'recipe-planner'
  location: location
  identity: {                                   // ← attach the app's managed identity
    type: 'UserAssigned'
    userAssignedIdentities: { '${appIdentity.id}': {} }
  }
  properties: {
    managedEnvironmentId: containerEnv.id       // ← reference → deploys after the env
    // Azure populates this when the app is created on a Consumption environment.
    // The template omitted it, so `what-if` reported it being DELETED — and a
    // container app with no workload profile is not a thing you want to find out
    // about during a deploy.
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      maxInactiveRevisions: 100
      ingress: {
        external: true
        targetPort: 3000
        traffic: [ { latestRevision: true, weight: 100 } ]
        stickySessions: { affinity: 'none' }   // Azure's default, declared so what-if stays quiet
      }
      registries: [ {
        server: 'ghcr.io'
        username: ghcrUsername
        // Secret name matches the live app. `az containerapp registry set`
        // generates its own name rather than reusing one you declare, which is
        // why this is not the `ghcr-pull-token` the template used to invent.
        passwordSecretRef: 'ghcrio-carlovinci17'
      } ]
      secrets: [
        { name: 'ghcrio-carlovinci17', value: ghcrPullToken }           // registry PAT (secure param)
        // Key Vault references — resolved by the app identity, so no secret
        // VALUES live in this template or in the deployment history.
        //
        // NOTE the casing: the vault holds these under SCREAMING-KEBAB names
        // (DATABASE-URL, AUTH-SECRET, …) except the two oldest, which are
        // lowercase. Key Vault secret names are case-sensitive, so a tidy-up
        // here would break every reference.
        { name: 'anthropic-api-key',             keyVaultUrl: '${kvUri}secrets/anthropic-api-key',                   identity: appIdentity.id }
        { name: 'appinsights-connection-string', keyVaultUrl: '${kvUri}secrets/appinsights-connection-string',       identity: appIdentity.id }
        { name: 'database-url',                  keyVaultUrl: '${kvUri}secrets/DATABASE-URL',                        identity: appIdentity.id }
        { name: 'auth-secret',                   keyVaultUrl: '${kvUri}secrets/AUTH-SECRET',                         identity: appIdentity.id }
        { name: 'entra-id',                      keyVaultUrl: '${kvUri}secrets/AUTH-MICROSOFT-ENTRA-ID-ID',          identity: appIdentity.id }
        { name: 'entra-secret',                  keyVaultUrl: '${kvUri}secrets/AUTH-MICROSOFT-ENTRA-ID-SECRET',      identity: appIdentity.id }
        { name: 'entra-issuer',                  keyVaultUrl: '${kvUri}secrets/AUTH-MICROSOFT-ENTRA-ID-ISSUER',      identity: appIdentity.id }
        { name: 'ingestion-secret',              keyVaultUrl: '${kvUri}secrets/INGESTION-INTERNAL-SECRET',           identity: appIdentity.id }
      ]
    }
    template: {
      containers: [ {
        name: 'recipe-planner'
        image: containerImage
        resources: { cpu: json('0.5'), memory: '1Gi' }
        // RECONCILED 2026-10-08 against the live app — all 18 variables.
        //
        // This list previously held 3. The other 15 had been added imperatively
        // with `az containerapp update` across Modules 4-11 and never written
        // back, so applying the template would have REPLACED the env array and
        // taken production down: no database, no auth, no background jobs.
        // (ARM incremental mode leaves out-of-template *resources* alone, but a
        // property of a resource the template *does* declare is overwritten
        // wholesale — which is exactly what this array is.)
        //
        // Keep it in step. Prove any change with `what-if` before applying:
        //   az deployment group what-if -g rg-recipe-planner -f infra/main.bicep \
        //     -p containerImage=<current> ghcrPullToken=<pat>
        //
        // READING THAT OUTPUT: a clean run is NOT "no changes". Three kinds of
        // diff are unavoidable noise, and knowing them is the difference
        // between spotting a real change and ignoring everything:
        //   1. Every entry in `configuration.secrets` shows as Modified.
        //      what-if diffs arrays BY POSITION, and the live order differs
        //      from this file's. Compare the name->keyVaultUrl *set* instead.
        //   2. `AZURE_CLIENT_ID` shows as Modified. Its value is a
        //      `reference()` that what-if cannot evaluate at plan time; it
        //      resolves to the same GUID.
        //   3. `runningStatus` and `ingress.exposedPort` show as Deleted.
        //      Both are read-only or Azure-populated and cannot be declared.
        // Anything OUTSIDE those three is a real change — look at it.
        env: [
          // Secret-backed (8) — values resolved from Key Vault at runtime.
          { name: 'ANTHROPIC_API_KEY',                     secretRef: 'anthropic-api-key' }
          { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', secretRef: 'appinsights-connection-string' }
          { name: 'DATABASE_URL',                          secretRef: 'database-url' }
          { name: 'AUTH_SECRET',                           secretRef: 'auth-secret' }
          { name: 'AUTH_MICROSOFT_ENTRA_ID_ID',            secretRef: 'entra-id' }
          { name: 'AUTH_MICROSOFT_ENTRA_ID_SECRET',        secretRef: 'entra-secret' }
          { name: 'AUTH_MICROSOFT_ENTRA_ID_ISSUER',        secretRef: 'entra-issuer' }
          { name: 'INGESTION_INTERNAL_SECRET',             secretRef: 'ingestion-secret' }

          // Plain (10). AI_PROVIDER is the only provider switch left after the
          // Supabase/Inngest decommission — the rest were deleted because each
          // had one working position and a missing one silently broke a feature.
          { name: 'AI_PROVIDER',              value: 'foundry' }
          { name: 'AZURE_STORAGE_ACCOUNT',    value: 'strpdevdtyzeg7l6ihh4' }
          { name: 'AZURE_WEBPUBSUB_ENDPOINT', value: 'https://wps-recipe-planner.webpubsub.azure.com' }
          { name: 'AZURE_FOUNDRY_ENDPOINT',   value: 'https://aif-recipe-planner.cognitiveservices.azure.com/' }
          { name: 'AZURE_FOUNDRY_DEPLOYMENT', value: 'gpt-4o-mini' }
          { name: 'FUNCTIONS_BASE_URL',       value: 'https://func-recipe-jobs.azurewebsites.net' }
          { name: 'NEXT_PUBLIC_APP_URL',      value: appPublicUrl }
          { name: 'NODE_ENV',                 value: 'production' }
          // Two that a codebase grep cannot prove are used, because a framework
          // reads them for itself. Both were on the "looks dead" side of the
          // decommission audit, and removing either takes production down:
          //   AUTH_URL        Auth.js builds the sign-in redirect from it
          //   AZURE_CLIENT_ID DefaultAzureCredential picks the managed identity
          { name: 'AUTH_URL',       value: appPublicUrl }
          { name: 'AZURE_CLIENT_ID', value: appIdentity.properties.clientId }
        ]
        // Health probes, declared rather than left to Azure's defaults. These
        // ARE the defaults it generated — but the template omitting them made
        // `what-if` report all three as DELETED, and an app with no readiness
        // probe takes traffic before Next is listening.
        probes: [
          { type: 'Liveness',  tcpSocket: { port: 3000 }, periodSeconds: 10, timeoutSeconds: 5, failureThreshold: 3,   successThreshold: 1 }
          { type: 'Readiness', tcpSocket: { port: 3000 }, periodSeconds: 5,  timeoutSeconds: 5, failureThreshold: 48,  successThreshold: 1 }
          { type: 'Startup',   tcpSocket: { port: 3000 }, periodSeconds: 1,  timeoutSeconds: 3, failureThreshold: 240, successThreshold: 1, initialDelaySeconds: 1 }
        ]
      } ]
      // maxReplicas is 10 live, not the 3 this template used to claim.
      scale: { minReplicas: 1, maxReplicas: 10 }
    }
  }
}


// ── Managed identities ─────────────────────────────────────────────
// The app's identity — reads secrets from Key Vault (Lesson 2.3)
resource appIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: 'id-recipe-planner'
  location: location
}

// The CI deploy identity — GitHub OIDC → Container Apps (Lesson 2.5)
resource deployIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: 'id-github-deploy'
  location: location
}

// ── Key Vault (RBAC authorization) — holds the app's secrets (2.3) ──
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    tenantId: subscription().tenantId
    sku: {
      family: 'A'
      name: 'standard'
    }
    enableRbacAuthorization: true
  }
}

// Secret VALUES are deliberately not managed here.
//
// This template used to declare `anthropic-api-key` with its value taken from a
// @secure() parameter. That makes the template destructive: re-applying it with
// a placeholder, or with a stale value, silently overwrites the live secret —
// and the deployment history then holds a record of a key nobody rotated.
// Removing the resource is safe: ARM incremental mode does not delete resources
// a template omits, so the live secret is untouched.
//
// Seed a FRESH vault with `bash scripts/seed-keyvault.sh`, which is where that
// knowledge belongs — a one-time bootstrap, not something re-run on every
// deploy. The App Insights string stays below because it is *derived* from a
// resource this template creates, so it is idempotent rather than a secret
// someone has to supply.
resource sAppI 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = { parent: keyVault, name: 'appinsights-connection-string', properties: { value: appInsights.properties.ConnectionString } }


// Built-in role IDs
var kvSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'
var contributorRoleId   = 'b24988ac-6180-42a0-ab88-20f7382dd24c'

// app identity → Key Vault Secrets User (read secrets)
resource appKvRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, appIdentity.id, kvSecretsUserRoleId)
  scope: keyVault
  properties: {
    principalId: appIdentity.properties.principalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', kvSecretsUserRoleId)
    principalType: 'ServicePrincipal'
  }
}

// deploy identity → Contributor on the resource group
resource deployRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(resourceGroup().id, deployIdentity.id, contributorRoleId)
  scope: resourceGroup()
  properties: {
    principalId: deployIdentity.properties.principalId
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', contributorRoleId)
    principalType: 'ServicePrincipal'
  }
}

// GitHub OIDC federated credential on the deploy identity (2.5)
// CI deploys from `main` — the old `gh-version2-plan` credential is gone.
// The subject must match the deploying branch exactly or the deploy step
// fails with AADSTS700213.
resource deployFic 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2023-01-31' = {
  parent: deployIdentity
  name: 'gh-main'
  properties: {
    issuer: 'https://token.actions.githubusercontent.com'
    subject: 'repo:carlovinci17/recipe-planner-app:ref:refs/heads/main'
    audiences: [ 'api://AzureADTokenExchange' ]
  }
}
