/**
 * Database types — hand-authored to match the migrations.
 *
 * In production this file is REGENERATED by:
 *   npm run db:types        (runs: supabase gen types typescript --local)
 *
 * The shape mirrors what `supabase gen types` produces so it plugs into
 * @supabase/supabase-js' generic inference. Don't deviate from this shape.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type UUID = string;
type Timestamp = string;

// ────────────────────────────────────────────────────────────────────
// Enum aliases — declared first so the table types can reference them
// ────────────────────────────────────────────────────────────────────
export type HouseholdRole = "owner" | "member";
export type RecipeSourceKind =
  | "manual"
  | "url"
  | "pdf"
  | "image"
  | "screenshot"
  | "google_drive"
  | "paste";
export type RecipeStatus = "draft" | "processing" | "needs_review" | "published" | "failed";
export type MealSlot = "breakfast" | "lunch" | "dinner" | "snack";
export type IngestionEventKind =
  | "file_uploaded"
  | "ingestion_requested"
  | "ai_processing_started"
  | "extraction_completed"
  | "validation_completed"
  | "recipe_ready_for_review"
  | "recipe_saved"
  | "failed";
export type IntegrationProvider = "google_drive";

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: UUID;
          email: string;
          entra_oid: string | null;
          display_name: string | null;
          avatar_url: string | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id: UUID;
          email: string;
          entra_oid?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          email?: string;
          entra_oid?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      households: {
        Row: {
          id: UUID;
          name: string;
          created_by: UUID;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          name: string;
          created_by: UUID;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          name?: string;
          created_by?: UUID;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      household_members: {
        Row: {
          household_id: UUID;
          user_id: UUID;
          role: HouseholdRole;
          joined_at: Timestamp;
        };
        Insert: {
          household_id: UUID;
          user_id: UUID;
          role?: HouseholdRole;
          joined_at?: Timestamp;
        };
        Update: {
          household_id?: UUID;
          user_id?: UUID;
          role?: HouseholdRole;
          joined_at?: Timestamp;
        };
        Relationships: [];
      };
      household_invites: {
        Row: {
          id: UUID;
          household_id: UUID;
          email: string;
          role: HouseholdRole;
          token: string;
          invited_by: UUID;
          expires_at: Timestamp;
          accepted_at: Timestamp | null;
          created_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          household_id: UUID;
          email: string;
          role?: HouseholdRole;
          token?: string;
          invited_by: UUID;
          expires_at?: Timestamp;
          accepted_at?: Timestamp | null;
          created_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          household_id?: UUID;
          email?: string;
          role?: HouseholdRole;
          token?: string;
          invited_by?: UUID;
          expires_at?: Timestamp;
          accepted_at?: Timestamp | null;
          created_at?: Timestamp;
        };
        Relationships: [];
      };
      recipes: {
        Row: {
          id: UUID;
          household_id: UUID;
          created_by: UUID;
          title: string;
          description: string | null;
          servings: number | null;
          prep_time_min: number | null;
          cook_time_min: number | null;
          total_time_min: number | null;
          notes: string | null;
          source_kind: RecipeSourceKind;
          source_url: string | null;
          source_metadata: Json;
          cover_image_path: string | null;
          image_paths: string[];
          nutrition: Json;
          ai_metadata: Json;
          ai_confidence: number | null;
          ai_model: string | null;
          cuisines: string[];
          meal_types: string[];
          diet_types: string[];
          cooking_methods: string[];
          difficulty: string | null;
          occasions: string[];
          tags: string[];
          rating: number | null;
          is_favorite: boolean;
          status: RecipeStatus;
          archived_at: Timestamp | null;
          embedding: number[] | null;
          search_tsv: unknown;
          ingestion_job_id: UUID | null;
          external_source_id: string | null;
          cover_focal_x: number;
          cover_focal_y: number;
          source_name: string | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          household_id: UUID;
          created_by: UUID;
          title: string;
          description?: string | null;
          servings?: number | null;
          prep_time_min?: number | null;
          cook_time_min?: number | null;
          notes?: string | null;
          source_kind?: RecipeSourceKind;
          source_url?: string | null;
          source_metadata?: Json;
          cover_image_path?: string | null;
          image_paths?: string[];
          nutrition?: Json;
          ai_metadata?: Json;
          ai_confidence?: number | null;
          ai_model?: string | null;
          cuisines?: string[];
          meal_types?: string[];
          diet_types?: string[];
          cooking_methods?: string[];
          difficulty?: string | null;
          occasions?: string[];
          tags?: string[];
          rating?: number | null;
          is_favorite?: boolean;
          status?: RecipeStatus;
          archived_at?: Timestamp | null;
          embedding?: number[] | null;
          ingestion_job_id?: UUID | null;
          external_source_id?: string | null;
          cover_focal_x?: number;
          cover_focal_y?: number;
          source_name?: string | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          household_id?: UUID;
          created_by?: UUID;
          title?: string;
          description?: string | null;
          servings?: number | null;
          prep_time_min?: number | null;
          cook_time_min?: number | null;
          notes?: string | null;
          source_kind?: RecipeSourceKind;
          source_url?: string | null;
          source_metadata?: Json;
          cover_image_path?: string | null;
          image_paths?: string[];
          nutrition?: Json;
          ai_metadata?: Json;
          ai_confidence?: number | null;
          ai_model?: string | null;
          cuisines?: string[];
          meal_types?: string[];
          diet_types?: string[];
          cooking_methods?: string[];
          difficulty?: string | null;
          occasions?: string[];
          tags?: string[];
          rating?: number | null;
          is_favorite?: boolean;
          status?: RecipeStatus;
          archived_at?: Timestamp | null;
          embedding?: number[] | null;
          ingestion_job_id?: UUID | null;
          external_source_id?: string | null;
          cover_focal_x?: number;
          cover_focal_y?: number;
          source_name?: string | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      recipe_ingredients: {
        Row: {
          id: UUID;
          recipe_id: UUID;
          position: number;
          section: string | null;
          raw_text: string;
          quantity: number | null;
          unit: string | null;
          ingredient: string | null;
          notes: string | null;
          optional: boolean;
          created_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          recipe_id: UUID;
          position: number;
          section?: string | null;
          raw_text: string;
          quantity?: number | null;
          unit?: string | null;
          ingredient?: string | null;
          notes?: string | null;
          optional?: boolean;
          created_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          recipe_id?: UUID;
          position?: number;
          section?: string | null;
          raw_text?: string;
          quantity?: number | null;
          unit?: string | null;
          ingredient?: string | null;
          notes?: string | null;
          optional?: boolean;
          created_at?: Timestamp;
        };
        Relationships: [];
      };
      recipe_instructions: {
        Row: {
          id: UUID;
          recipe_id: UUID;
          position: number;
          section: string | null;
          text: string;
          duration_min: number | null;
          created_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          recipe_id: UUID;
          position: number;
          section?: string | null;
          text: string;
          duration_min?: number | null;
          created_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          recipe_id?: UUID;
          position?: number;
          section?: string | null;
          text?: string;
          duration_min?: number | null;
          created_at?: Timestamp;
        };
        Relationships: [];
      };
      recipe_ratings: {
        Row: {
          recipe_id: UUID;
          user_id: UUID;
          rating: number;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          recipe_id: UUID;
          user_id: UUID;
          rating: number;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          recipe_id?: UUID;
          user_id?: UUID;
          rating?: number;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      ingestion_jobs: {
        Row: {
          id: UUID;
          household_id: UUID;
          created_by: UUID;
          recipe_id: UUID | null;
          source_kind: RecipeSourceKind;
          source_url: string | null;
          storage_path: string | null;
          storage_bucket: string | null;
          page_image_paths: string[];
          status: RecipeStatus;
          error: string | null;
          ai_model: string | null;
          prompt_tokens: number | null;
          completion_tokens: number | null;
          cost_cents: number | null;
          raw_extraction: Json | null;
          normalized: Json | null;
          inngest_run_id: string | null;
          attempts: number;
          external_file_id: string | null;
          external_modified_time: Timestamp | null;
          skim_results: Json | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          household_id: UUID;
          created_by: UUID;
          recipe_id?: UUID | null;
          source_kind: RecipeSourceKind;
          source_url?: string | null;
          storage_path?: string | null;
          storage_bucket?: string | null;
          page_image_paths?: string[];
          status?: RecipeStatus;
          error?: string | null;
          ai_model?: string | null;
          prompt_tokens?: number | null;
          completion_tokens?: number | null;
          cost_cents?: number | null;
          raw_extraction?: Json | null;
          normalized?: Json | null;
          inngest_run_id?: string | null;
          attempts?: number;
          external_file_id?: string | null;
          external_modified_time?: Timestamp | null;
          skim_results?: Json | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          household_id?: UUID;
          created_by?: UUID;
          recipe_id?: UUID | null;
          source_kind?: RecipeSourceKind;
          source_url?: string | null;
          storage_path?: string | null;
          storage_bucket?: string | null;
          page_image_paths?: string[];
          status?: RecipeStatus;
          error?: string | null;
          ai_model?: string | null;
          prompt_tokens?: number | null;
          completion_tokens?: number | null;
          cost_cents?: number | null;
          raw_extraction?: Json | null;
          normalized?: Json | null;
          inngest_run_id?: string | null;
          attempts?: number;
          external_file_id?: string | null;
          external_modified_time?: Timestamp | null;
          skim_results?: Json | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      ingestion_events: {
        Row: {
          id: UUID;
          job_id: UUID;
          kind: IngestionEventKind;
          payload: Json;
          created_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          job_id: UUID;
          kind: IngestionEventKind;
          payload?: Json;
          created_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          job_id?: UUID;
          kind?: IngestionEventKind;
          payload?: Json;
          created_at?: Timestamp;
        };
        Relationships: [];
      };
      planner_entries: {
        Row: {
          id: UUID;
          household_id: UUID;
          recipe_id: UUID | null;
          custom_title: string | null;
          date: string;
          slot: MealSlot;
          servings: number | null;
          notes: string | null;
          position: number;
          created_by: UUID;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          household_id: UUID;
          recipe_id?: UUID | null;
          custom_title?: string | null;
          date: string;
          slot: MealSlot;
          servings?: number | null;
          notes?: string | null;
          position?: number;
          created_by: UUID;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          household_id?: UUID;
          recipe_id?: UUID | null;
          custom_title?: string | null;
          date?: string;
          slot?: MealSlot;
          servings?: number | null;
          notes?: string | null;
          position?: number;
          created_by?: UUID;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      shopping_lists: {
        Row: {
          id: UUID;
          household_id: UUID;
          name: string;
          week_start: string | null;
          is_active: boolean;
          created_by: UUID;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          household_id: UUID;
          name?: string;
          week_start?: string | null;
          is_active?: boolean;
          created_by: UUID;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          household_id?: UUID;
          name?: string;
          week_start?: string | null;
          is_active?: boolean;
          created_by?: UUID;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      shopping_list_items: {
        Row: {
          id: UUID;
          list_id: UUID;
          ingredient: string;
          quantity: number | null;
          unit: string | null;
          category: string | null;
          source_recipe_ids: UUID[];
          custom: boolean;
          is_checked: boolean;
          position: number;
          notes: string | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          list_id: UUID;
          ingredient: string;
          quantity?: number | null;
          unit?: string | null;
          category?: string | null;
          source_recipe_ids?: UUID[];
          custom?: boolean;
          is_checked?: boolean;
          position?: number;
          notes?: string | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          list_id?: UUID;
          ingredient?: string;
          quantity?: number | null;
          unit?: string | null;
          category?: string | null;
          source_recipe_ids?: UUID[];
          custom?: boolean;
          is_checked?: boolean;
          position?: number;
          notes?: string | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      integration_accounts: {
        Row: {
          id: UUID;
          household_id: UUID;
          user_id: UUID;
          provider: IntegrationProvider;
          external_id: string;
          email: string | null;
          access_token: string;
          refresh_token: string | null;
          scopes: string[];
          expires_at: Timestamp | null;
          metadata: Json;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          household_id: UUID;
          user_id: UUID;
          provider: IntegrationProvider;
          external_id: string;
          email?: string | null;
          access_token: string;
          refresh_token?: string | null;
          scopes?: string[];
          expires_at?: Timestamp | null;
          metadata?: Json;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          household_id?: UUID;
          user_id?: UUID;
          provider?: IntegrationProvider;
          external_id?: string;
          email?: string | null;
          access_token?: string;
          refresh_token?: string | null;
          scopes?: string[];
          expires_at?: Timestamp | null;
          metadata?: Json;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      drive_file_index: {
        Row: {
          id: UUID;
          household_id: UUID;
          drive_file_id: string;
          file_name: string;
          folder_path: string;
          mime_type: string;
          modified_time: Timestamp | null;
          index_status: string;
          index_method: string | null;
          current_page: number | null;
          total_pages: number | null;
          recipe_titles: string[];
          indexed_at: Timestamp | null;
          error: string | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          household_id: UUID;
          drive_file_id: string;
          file_name: string;
          folder_path?: string;
          mime_type: string;
          modified_time?: Timestamp | null;
          index_status?: string;
          index_method?: string | null;
          current_page?: number | null;
          total_pages?: number | null;
          recipe_titles?: string[];
          indexed_at?: Timestamp | null;
          error?: string | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          household_id?: UUID;
          drive_file_id?: string;
          file_name?: string;
          folder_path?: string;
          mime_type?: string;
          modified_time?: Timestamp | null;
          index_status?: string;
          index_method?: string | null;
          current_page?: number | null;
          total_pages?: number | null;
          recipe_titles?: string[];
          indexed_at?: Timestamp | null;
          error?: string | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
      drive_watched_folders: {
        Row: {
          id: UUID;
          account_id: UUID;
          household_id: UUID;
          folder_id: string;
          folder_name: string | null;
          page_token: string | null;
          is_active: boolean;
          last_synced_at: Timestamp | null;
          created_at: Timestamp;
          updated_at: Timestamp;
        };
        Insert: {
          id?: UUID;
          account_id: UUID;
          household_id: UUID;
          folder_id: string;
          folder_name?: string | null;
          page_token?: string | null;
          is_active?: boolean;
          last_synced_at?: Timestamp | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Update: {
          id?: UUID;
          account_id?: UUID;
          household_id?: UUID;
          folder_id?: string;
          folder_name?: string | null;
          page_token?: string | null;
          is_active?: boolean;
          last_synced_at?: Timestamp | null;
          created_at?: Timestamp;
          updated_at?: Timestamp;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      create_household_with_owner: {
        Args: { _name: string };
        Returns: UUID;
      };
      accept_household_invite: {
        Args: { _token: string };
        Returns: UUID;
      };
      generate_shopping_list_from_planner: {
        Args: { _household_id: UUID; _week_start: string };
        Returns: UUID;
      };
      generate_shopping_list_from_planner_range: {
        Args: { _household_id: UUID; _start_date: string; _num_days: number };
        Returns: UUID;
      };
      is_household_member: {
        Args: { _household_id: UUID; _user_id: UUID };
        Returns: boolean;
      };
      is_household_owner: {
        Args: { _household_id: UUID; _user_id: UUID };
        Returns: boolean;
      };
    };
    Enums: {
      household_role: HouseholdRole;
      recipe_source_kind: RecipeSourceKind;
      recipe_status: RecipeStatus;
      meal_slot: MealSlot;
      ingestion_event_kind: IngestionEventKind;
      integration_provider: IntegrationProvider;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// ────────────────────────────────────────────────────────────────────
// Convenience helpers
// ────────────────────────────────────────────────────────────────────
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
