#!/usr/bin/env bash
#
# Rebuild .env.local for local development from Azure.
#
# Why this exists: .env.local is gitignored, so it is the one file in this repo
# with no backup. On 2026-10-04 it was overwritten with .env.example, which
# wiped all 20 post-cutover variables (AUTH_PROVIDER, DATABASE_URL, the Entra
# block, ...) and left every page returning HTTP 500 - middleware fell back to
# the Supabase auth path and tried to build a client for a deleted project.
#
# Everything needed is already in Azure, because that is where production
# reads it from:
#   - plain values  -> the recipe-planner container app's env block
#   - secrets       -> Key Vault kv-recipe-planner
#
# Four values are deliberately NOT the production ones. See LOCAL OVERRIDES.
#
# Usage:
#   az login                       # if not already signed in
#   bash scripts/pull-local-env.sh
#
# Kept ASCII-only, and every expansion braced. A bare $VAR immediately
# followed by a multi-byte character has those bytes absorbed into the
# variable name, so `echo "$OUT..."` with a real ellipsis looked up a
# variable named OUT-plus-ellipsis and `set -u` made that fatal.

set -euo pipefail

KV="kv-recipe-planner"
OUT=".env.local"

cd "$(dirname "$0")/.."

if ! command -v az >/dev/null 2>&1; then
  echo "ERROR: the Azure CLI (az) is not installed" >&2
  exit 1
fi
if ! az account show >/dev/null 2>&1; then
  echo "ERROR: not signed in to Azure - run: az login" >&2
  exit 1
fi

# Never clobber an existing file without a copy: it may be the only one.
if [ -f "${OUT}" ]; then
  BACKUP="${OUT}.bak.$(date +%Y%m%d-%H%M%S)"
  cp "${OUT}" "${BACKUP}"
  echo "- backed up existing ${OUT} -> ${BACKUP}"
fi

# PULL_ENV_FAKE_SECRETS=1 swaps in dummy values so the file composition can be
# tested end to end without touching Key Vault.
secret() {
  local name="$1"
  local v
  if [ "${PULL_ENV_FAKE_SECRETS:-0}" = "1" ]; then
    printf 'FAKE-%s' "${name}"
    return 0
  fi
  if ! v=$(az keyvault secret show --vault-name "${KV}" --name "${name}" --query value -o tsv 2>/dev/null); then
    echo "ERROR: could not read secret '${name}' from ${KV}" >&2
    echo "       Check you have 'Key Vault Secrets User' on the vault." >&2
    exit 1
  fi
  if [ -z "${v}" ]; then
    echo "ERROR: secret '${name}' came back empty" >&2
    exit 1
  fi
  printf '%s' "${v}"
}

echo "- reading secrets from Key Vault (${KV})"
DB_URL=$(secret DATABASE-URL)
AUTH_SECRET_VALUE=$(secret AUTH-SECRET)
ENTRA_ID=$(secret AUTH-MICROSOFT-ENTRA-ID-ID)
ENTRA_SECRET=$(secret AUTH-MICROSOFT-ENTRA-ID-SECRET)
ENTRA_ISSUER=$(secret AUTH-MICROSOFT-ENTRA-ID-ISSUER)
ANTHROPIC_KEY=$(secret anthropic-api-key)

echo "- composing ${OUT}"

# Unquoted heredoc on purpose: the ${...} below must expand. Nothing inside
# contains a backtick or a literal $ that needs to survive.
cat > "${OUT}" <<ENVFILE
# Local development. Generated by scripts/pull-local-env.sh from the
# recipe-planner container app + Key Vault ${KV}.
# Regenerate any time with: bash scripts/pull-local-env.sh
#
# NOT in git (gitignored, and it holds secrets). If you lose it, re-run the
# script rather than hand-rebuilding it.

# --- Provider switches: the post-cutover stack (Module 11) -------------
# These are what was missing when the file got overwritten. Losing
# AUTH_PROVIDER alone is enough to 500 every page: middleware falls back to
# the Supabase auth path and builds a client for a deleted project.
AUTH_PROVIDER=entra
STORAGE_PROVIDER=azure
REALTIME_PROVIDER=azure
JOBS_PROVIDER=durable
AI_PROVIDER=foundry
# Client-side twins - the browser bundle cannot read the server-only names.
NEXT_PUBLIC_STORAGE_PROVIDER=azure
NEXT_PUBLIC_REALTIME_PROVIDER=azure

# --- Neon Postgres ----------------------------------------------------
# NEON_DATABASE_URL is the same connection under a second name: the app
# reads DATABASE_URL, the scripts/ folder reads NEON_DATABASE_URL.
DATABASE_URL=${DB_URL}
NEON_DATABASE_URL=${DB_URL}

# --- Auth.js + Microsoft Entra External ID ----------------------------
AUTH_SECRET=${AUTH_SECRET_VALUE}
AUTH_MICROSOFT_ENTRA_ID_ID=${ENTRA_ID}
AUTH_MICROSOFT_ENTRA_ID_SECRET=${ENTRA_SECRET}
AUTH_MICROSOFT_ENTRA_ID_ISSUER=${ENTRA_ISSUER}

# --- Azure services (keyless: uses your own az login) -----------------
# AZURE_CLIENT_ID is deliberately NOT set. In production it names the
# container app's managed identity; setting it locally makes
# DefaultAzureCredential hunt for an identity that is not on this machine.
AZURE_STORAGE_ACCOUNT=strpdevdtyzeg7l6ihh4
AZURE_WEBPUBSUB_ENDPOINT=https://wps-recipe-planner.webpubsub.azure.com
AZURE_FOUNDRY_ENDPOINT=https://aif-recipe-planner.cognitiveservices.azure.com/
AZURE_FOUNDRY_DEPLOYMENT=gpt-4o-mini

# --- LOCAL OVERRIDES: intentionally different from production ----------
# Auth.js builds its sign-in redirect from AUTH_URL, so this must match a
# redirect URI registered on the Entra app or sign-in fails (AADSTS50011).
AUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Durable Functions: the deployed host in prod, your local func start here.
FUNCTIONS_BASE_URL=http://localhost:7071

# Shared secret the app and the Functions host authenticate to each other
# with. MUST match functions/local.settings.json - a mismatch makes every
# ingestion step fail with 403.
INGESTION_INTERNAL_SECRET=dev-local-secret-change-me

# --- Anthropic --------------------------------------------------------
# AI_PROVIDER=foundry above, so this is only read by the golden-set tests
# and the legacy Anthropic path.
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
ANTHROPIC_MODEL_VISION=claude-opus-4-7
ANTHROPIC_MODEL_TEXT=claude-opus-4-7
ANTHROPIC_MODEL_FAST=claude-haiku-4-5

# --- Supabase: RETIRED, project deleted -------------------------------
# Left BLANK on purpose, not placeholder. lib/env.ts treats empty as absent;
# a short placeholder value is what broke the dev server on 2026-10-04.
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

LOG_LEVEL=debug
ENVFILE

chmod 600 "${OUT}"

VAR_COUNT=$(grep -cvE '^[[:space:]]*(#|$)' "${OUT}" || true)
echo "OK: wrote ${OUT} (${VAR_COUNT} variables, mode 600)"
echo
echo "Next:"
echo "  1. restart the dev server so it picks up the new file"
echo "  2. check http://localhost:3000/login returns 200"
